name:Workflow
on:
  push
    branches:
      - feat-devsecops

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
      - name:Checkout code
        uses: actions/checkout@v3

      - name: HOLA MUNDO
        run: |
          echo "HOLA MUNDO"
          echo "curso devsecops"


      

      
  
 



